version: '3.9'
services:
  postgres-db:
    image: postgres:latest
    container_name: collabtable-postgres
    environment:
      - TZ=Europe/Zagreb
      - POSTGRES_DB=collabtable
      - POSTGRES_USER=collabtable
      - POSTGRES_PASSWORD=collabtable
    ports:
      - "5432:5432"
    volumes:
      - "./database:/docker-entrypoint-initdb.d:ro"
      - collabtable-pgdata:/var/lib/postgresql/data
  auth-service:
    image: collabtable-auth
    container_name: collabtable-auth-service
    depends_on:
      - "postgres-db"
    ports:
      - "9090:9090"
  workspace-service:
    image: collabtable-workspace
    container_name: collabtable-workspace-service
    depends_on:
      - "postgres-db"
    ports:
      - "9091:9090"
  notification-service:
    image: collabtable-notifications
    container_name: collabtable-notification-service
    ports:
      - "9092:9090"

volumes:
  collabtable-pgdata: