server:
  port: ${SERVER_PORT}
  secret: ${JWT_SECRET}
  allowedOrigins: ${SERVER_ALLOWED_ORIGINS}
  debug: ${SERVER_DEBUG_MODE}
  systemUuid: ${SERVER_SYSTEM_UUID}
  timeout:
    idle: 120
    read: 1
    write: 1
    shutdown: 30

mailer:
  key: ${SENDGRID_API_KEY}
  from:
    email: ${MAILER_EMAIL_FROM}
    name: ${MAILER_EMAIL_NAME}

services:
  audit: ${AUDIT_SERVICE_HOST}