server:
  port: 9998
  allowedOrigins: ["*"]
  timeout:
    idle: 120
    read: 1
    write: 1
    shutdown: 30

database:
  name: collabtable
  ip: postgres-db
  port: 5432
  schema: workspace
  username: collabtable
  password: collabtable
  logger:
    level: 0 # 0: debug, 1: info, 2: warning, 3: error, 4: none, 5: unknown

authorization:
  address: http://auth-service:9090/user

notification:
  address: http://notification-service:9090