server:
  port: ${SERVER_PORT}
  secret: ${JWT_SECRET}
  allowedOrigins: ${SERVER_ALLOWED_ORIGINS}
  debug: ${SERVER_DEBUG_MODE}
  systemUuid: ${SERVER_SYSTEM_UUID}
  timeout:
    idle: 120
    read: 1
    write: 1
    shutdown: 30

database:
  name: ${DATABASE_NAME}
  ip: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  schema: ${DATABASE_SCHEMA}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  logger:
    level: 0 # 0: debug, 1: info, 2: warning, 3: error, 4: none, 5: unknown
    
services:
  audit: ${AUDIT_SERVICE_HOST}
  notification: ${NOTIFICATION_SERVICE_HOST}