apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
  labels:
    name: audit
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: audit
  template:
    metadata:
      annotations: {}
      labels:
        name: audit
    spec:
      serviceAccountName: {{ include "airtable.serviceAccountName" . }}
      containers:
        - name: audit          
          image: "{{ .Values.audit.image }}:{{ .Values.audit.version }}"
          imagePullPolicy: {{ .Values.audit.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: containers
                  key: audit
            - name: DATABASE_HOST
              value: airtable-airtabledb
            - name: DATABASE_SCHEMA
              value: audit
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: postgresql-name
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airtable-airtabledb
                  key: postgres-password
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: containers
                  key: db
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: postgresql-username
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: value
            - name: SERVER_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: containers
                  key: allowedOrigins
            - name: SERVER_DEBUG_MODE
              valueFrom:
                secretKeyRef:
                  name: containers
                  key: debug
            - name: SERVER_SYSTEM_UUID
              valueFrom:
                secretKeyRef:
                  name: system-uuid
                  key: value
          ports:
            - name: audit-http
              containerPort: 9996
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: audit-http
          readinessProbe:
            httpGet:
              path: /health
              port: audit-http

      
