apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace
  labels:
    name: workspace
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: workspace
  template:
    metadata:
      annotations: {}
      labels:
        name: workspace
    spec:
      serviceAccountName: {{ include "airtable.serviceAccountName" . }}
      containers:
        - name: workspace          
          image: "{{ .Values.workspace.image }}:{{ .Values.workspace.version }}"
          imagePullPolicy: {{ .Values.workspace.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: containers
                  key: workspace
            - name: DATABASE_HOST
              value: airtable-airtabledb
            - name: DATABASE_SCHEMA
              value: workspace
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: postgresql-name
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airtable-airtabledb
                  key: postgres-password
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: containers
                  key: db
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: postgresql-username
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: value
            - name: SERVER_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: containers
                  key: allowedOrigins
            - name: SERVER_DEBUG_MODE
              valueFrom:
                secretKeyRef:
                  name: containers
                  key: debug
            - name: SERVER_SYSTEM_UUID
              valueFrom:
                secretKeyRef:
                  name: system-uuid
                  key: value
            - name: AUDIT_SERVICE_HOST
              value: http://audit-service
          ports:
            - name: work-http
              containerPort: 9998
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: work-http
          readinessProbe:
            httpGet:
              path: /health
              port: work-http

      
