version: '3.9'
services:
  postgres-db:
    image: postgres:latest
    container_name: airtable-postgres
    environment:
      - TZ=Europe/Zagreb
      - POSTGRES_DB=airtable
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./database:/docker-entrypoint-initdb.d:ro"
      - airtable-pgdata:/var/lib/postgresql/data
  auth-service:
    image: airtable-service-auth
    container_name: airtable-auth-service
    depends_on:
      - "postgres-db"
    ports:
      - "9999:9999"
  workspace-service:
    image: airtable-service-workspace
    container_name: airtable-workspace-service
    depends_on:
      - "postgres-db"
    ports:
      - "9998:9998"
  notification-service:
    image: airtable-service-notifications
    container_name: airtable-notification-service
    ports:
      - "9997:9997"
  audit-service:
    image: airtable-service-audit
    container_name: airtable-audit-service
    depends_on:
      - "postgres-db"
    ports:
      - "9996:9996"
  meta-service:
    image: airtable-service-meta
    container_name: airtable-meta-service
    depends_on:
      - "postgres-db"
    ports:
      - "9995:9995"
  data-service:
    image: airtable-service-data
    container_name: airtable-data-service
    depends_on:
      - "postgres-db"
    ports:
      - "9994:9994"

volumes:
  airtable-pgdata: