version: '3.9'
services:
  postgres-db:
    image: postgres:latest
    container_name: airtable-postgres
    environment:
      - TZ=Europe/Zagreb
      - POSTGRES_DB=airtable
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./database:/docker-entrypoint-initdb.d:ro"
      - airtable-pgdata:/var/lib/postgresql/data
    networks:
      - isolation-network
  auth-service:
    image: airtable-service-auth
    container_name: airtable-auth-service
    env_file:
      - ../services/service-auth/.env
    depends_on:
      - "postgres-db"
    ports:
      - "9999:9999"
    networks:
      - isolation-network
  workspace-service:
    image: airtable-service-workspace
    container_name: airtable-workspace-service
    env_file:
      - ../services/service-workspace/.env
    depends_on:
      - "postgres-db"
    ports:
      - "9998:9998"
    networks:
      - isolation-network
  notification-service:
    image: airtable-service-notifications
    container_name: airtable-notification-service
    env_file:
      - ../services/service-notification/.env
    ports:
      - "9997:9997"
    networks:
      - isolation-network
  audit-service:
    image: airtable-service-audit
    container_name: airtable-audit-service
    env_file:
      - ../services/service-audit/.env
    depends_on:
      - "postgres-db"
    ports:
      - "9996:9996"
    networks:
      - isolation-network
  meta-service:
    image: airtable-service-meta
    container_name: airtable-meta-service
    env_file:
      - ../services/service-meta/.env
    depends_on:
      - "postgres-db"
    ports:
      - "9995:9995"
    networks:
      - isolation-network
  data-service:
    image: airtable-service-data
    container_name: airtable-data-service
    env_file:
      - ../services/service-data/.env
    depends_on:
      - "postgres-db"
    ports:
      - "9994:9994"
    networks:
      - isolation-network

networks:
  isolation-network:
    driver: bridge

volumes:
  airtable-pgdata: