---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  value: MjEyMyomKComQCooOTg3OWF7Lz1d
---
apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  postgresql-username: cG9zdGdyZXM=
  postgresql-name: YWlydGFibGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: system-uuid
type: Opaque
data:
  value: MTc0OWQxNGQtMTgxYi00ZTg3LWJiYzEtNGE5ZDAyMGI2YTVl
---
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-key
type: Opaque
data:
  key: QWRtaW4= #TODO add base64 encoded sendgrid key
  from: QWRtaW4= #TODO add base64 encoded sendgrid email
  name: QWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: containers
type: Opaque
data:
  debug: ZmFsc2U=
  db: NTQzMg==
  auth: OTk5OQ==
  allowedOrigins: WycqJ10=
  audit: OTk5Ng==
  notification: OTk5Nw==
  workspace: OTk5OA==
  meta: OTk5NQ==
  data: OTk5NA==
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend
type: Opaque
data:
  baseUrl: aHR0cDovL2xvY2FsaG9zdC9hcGk=
