# Default values for airtable.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  auth:
    - name: auth-service
      type: NodePort
      port: 80
  audit:
    - name: audit-service
      type: NodePort
      port: 80
  workspace:
    - name: workspace-service
      type: NodePort
      port: 80
  meta:
    - name: meta-service
      type: NodePort
      port: 80
  data:
    - name: data-service
      type: NodePort
      port: 80
  notification:
    - name: notification-service
      type: ClusterIP
      port: 80

ingress:
  enabled: true
  host: ""
  tlsEnabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

airtable-db:
  image:
    tag: 14.5.0
  persistence:
    size: 8Gi
  existingSecret: database
  resources:
    requests:
      cpu: 300m
      memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
