replicaCount: 1

serviceAccount:
  create: true
  annotations: { }
  name:

ingress-nginx:
  controller:
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    service:
      externalTrafficPolicy: Local

auth:
  image: airtable-service-auth
  pullPolicy: Never
  version: latest

audit:
  image: airtable-service-audit
  pullPolicy: Never
  version: latest

notification:
  image: airtable-service-notifications
  pullPolicy: Never
  version: latest

workspace:
  image: airtable-service-workspace
  pullPolicy: Never
  version: latest

meta:
  image: airtable-service-meta
  pullPolicy: Never
  version: latest

data:
  image: airtable-service-data
  pullPolicy: Never
  version: latest
  
frontend:
  image: airtable-service-frontend
  pullPolicy: Never
  version: latest

resources:
  requests:
    cpu: 400m
    memory: 1024Mi
  limits:
    cpu: 600m
    memory: 1536Mi

airtabledb:
  image:
    tag: 14.5.0
  auth:
    database: "airtable"
  persistence:
    size: 8Gi
  existingSecret: database
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
